# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d4266182f7a946804e9c9c943639200"
name = "tm01"
handle = "tm01"
application_url = "https://observed-protection-syndicate-tanks.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wac-demo-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping,write_shipping"

[auth]
redirect_urls = [
  "https://observed-protection-syndicate-tanks.trycloudflare.com/auth/callback",
  "https://observed-protection-syndicate-tanks.trycloudflare.com/auth/shopify/callback",
  "https://observed-protection-syndicate-tanks.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
